// Static list of all 30 NBA teams for seeding and TeamPicker
export const NBA_TEAMS = [
  { id: 1, name: "Hawks", abbreviation: "ATL", city: "Atlanta", conference: "East", division: "Southeast" },
  { id: 2, name: "Celtics", abbreviation: "BOS", city: "Boston", conference: "East", division: "Atlantic" },
  { id: 3, name: "Nets", abbreviation: "BKN", city: "Brooklyn", conference: "East", division: "Atlantic" },
  { id: 4, name: "Hornets", abbreviation: "CHA", city: "Charlotte", conference: "East", division: "Southeast" },
  { id: 5, name: "Bulls", abbreviation: "CHI", city: "Chicago", conference: "East", division: "Central" },
  { id: 6, name: "Cavaliers", abbreviation: "CLE", city: "Cleveland", conference: "East", division: "Central" },
  { id: 7, name: "Mavericks", abbreviation: "DAL", city: "Dallas", conference: "West", division: "Southwest" },
  { id: 8, name: "Nuggets", abbreviation: "DEN", city: "Denver", conference: "West", division: "Northwest" },
  { id: 9, name: "Pistons", abbreviation: "DET", city: "Detroit", conference: "East", division: "Central" },
  { id: 10, name: "Warriors", abbreviation: "GSW", city: "Golden State", conference: "West", division: "Pacific" },
  { id: 11, name: "Rockets", abbreviation: "HOU", city: "Houston", conference: "West", division: "Southwest" },
  { id: 12, name: "Pacers", abbreviation: "IND", city: "Indiana", conference: "East", division: "Central" },
  { id: 13, name: "Clippers", abbreviation: "LAC", city: "Los Angeles", conference: "West", division: "Pacific" },
  { id: 14, name: "Lakers", abbreviation: "LAL", city: "Los Angeles", conference: "West", division: "Pacific" },
  { id: 15, name: "Grizzlies", abbreviation: "MEM", city: "Memphis", conference: "West", division: "Southwest" },
  { id: 16, name: "Heat", abbreviation: "MIA", city: "Miami", conference: "East", division: "Southeast" },
  { id: 17, name: "Bucks", abbreviation: "MIL", city: "Milwaukee", conference: "East", division: "Central" },
  { id: 18, name: "Timberwolves", abbreviation: "MIN", city: "Minnesota", conference: "West", division: "Northwest" },
  { id: 19, name: "Pelicans", abbreviation: "NOP", city: "New Orleans", conference: "West", division: "Southwest" },
  { id: 20, name: "Knicks", abbreviation: "NYK", city: "New York", conference: "East", division: "Atlantic" },
  { id: 21, name: "Thunder", abbreviation: "OKC", city: "Oklahoma City", conference: "West", division: "Northwest" },
  { id: 22, name: "Magic", abbreviation: "ORL", city: "Orlando", conference: "East", division: "Southeast" },
  { id: 23, name: "76ers", abbreviation: "PHI", city: "Philadelphia", conference: "East", division: "Atlantic" },
  { id: 24, name: "Suns", abbreviation: "PHX", city: "Phoenix", conference: "West", division: "Pacific" },
  { id: 25, name: "Trail Blazers", abbreviation: "POR", city: "Portland", conference: "West", division: "Northwest" },
  { id: 26, name: "Kings", abbreviation: "SAC", city: "Sacramento", conference: "West", division: "Pacific" },
  { id: 27, name: "Spurs", abbreviation: "SAS", city: "San Antonio", conference: "West", division: "Southwest" },
  { id: 28, name: "Raptors", abbreviation: "TOR", city: "Toronto", conference: "East", division: "Atlantic" },
  { id: 29, name: "Jazz", abbreviation: "UTA", city: "Utah", conference: "West", division: "Northwest" },
  { id: 30, name: "Wizards", abbreviation: "WAS", city: "Washington", conference: "East", division: "Southeast" },
];
